### ISSUE TITLE
Font is barely readable

### ISSUE THREAD

**Issue by fvsch** [w3c/respec-docs#25]
Lato Light, as most light fonts, is hard to read in body copy sizes (16px here). A design rule of thumb, often broken with the thin type trend in recent years, is to avoid thin type below 20px.

This problem is especially strong with low density screens (aka ordinary laptop/desktop screens, in the 80-120ppi range). Thin strokes that look crisp on high density screens look brittle and make readers squint in lower density screens.

Look at http://www.w3.org/respec/guide.html#basic-layout on any low density screen, especially (but not only) on Windows. The body copy (Lato Light) looks fragile, alternating dark gray and light gray in different letter parts, while the code sample (Consolas Regular in my case, but should be similar with Menlo Regular) looks sturdy and is twice as easy on the eyes.

Typical solutions include:
1. Load Lato Regular as well, use the regular weight for body copy and the Light weight for headings and big text.
2. Avoid light text altogether (whether using Lato or a different typeface).

**Comment by halindrome** [comment]
I strongly agree with this.  The current version is actually unreadable on
(this) chromebook with default sizes.

On Tue, Mar 17, 2015 at 5:37 AM, fvsch notifications@github.com wrote:

> Lato Light, as most light fonts, is hard to read in body copy sizes (16px
> here). A design rule of thumb, often broken with the thin type trend in
> recent years, is to avoid thin type below 20px.
> 
> This problem is especially strong with low density screens (aka ordinary
> laptop/desktop screens, in the 80-120ppi range). Thin strokes that look
> crisp on high density screens look brittle and make readers squint in lower
> density screens.
> 
> Look at http://www.w3.org/respec/guide.html#basic-layout on any low
> density screen, especially (but not only) on Windows. The body copy (Lato
> Light) looks fragile, alternating dark gray and light gray in different
> letter parts, while the code sample (Consolas Regular in my case, but
> should be similar with Menlo Regular) looks sturdy and is twice as easy on
> the eyes.
> 
> Typical solutions include:
> 1. Load Lato Regular as well, use the regular weight for body copy and
>    the Light weight for headings and big text.
> 2. Avoid light text altogether (whether using Lato or a different
>    typeface).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/respec-docs/issues/25.

## 

Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Agree, it's even hard to read on my 27" single density display without zooming in.

**Comment by marcoscaceres** [comment]
Who can do the PR? I can do it in a day or two.
