### ISSUE TITLE
Best Practice Summary function broken

### ISSUE THREAD

**Issue by philarcher** [w3c/respec-docs#43]
ReSpec includes (or used to include) a very useful function for Best Practices documents that auto-generated summary lists. Inserting &lt;section id="bp-summary"&gt; &lt;/section&gt; used to work very nicely.

We use this in http://w3c.github.io/dwbp/bp.html and http://w3c.github.io/sdw/bp/ for example.

It ceased functioning with the new stylesheet and it would be really good to have it back, please?

**Comment by halindrome** [comment]
Huh - I had no idea it had that feature.  That's awesome.  I will look into it.

**Comment by halindrome** [comment]
That's not ReSpec.  That's code in your source that builds the list up.  Starts around line 44.

**Comment by marcoscaceres** [comment]
Should we consider adding this as a plugin?

**Comment by halindrome** [comment]
I have been thinking about it in general - things like lists of figures
etc.  I think it is a reasonable feature to support.

On Sun, Mar 6, 2016 at 1:36 AM, Marcos Caceres notifications@github.com
wrote:

> Should we consider adding this as a plugin?
> 
> Sent from my iPhone
> 
> > On 3 Mar 2016, at 1:38 AM, Shane McCarron notifications@github.com
> > wrote:
> > 
> > That's not ReSpec. That's code in your source that builds the list up.
> > Starts around line 44.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/respec-docs/issues/43#issuecomment-192821368.

## 

Shane McCarron
halindrome@gmail.com

**Comment by philarcher** [comment]
I am delighted to see that this has been fixed. Thank you very much, on behalf of the DWBP and SDW WG editors.

**Comment by halindrome** [comment]
You are welcome.  Note that I was completely unaware of the general feature that is built into ReSpec.   Sad that the thing is so complex I don't know all of its features now!
